spring:
  application:
    name: item-service
  cloud: 
   config: 
     override-none: true  
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2001/eureka
