spring:
  application:
    name: order-service  
  cloud: 
   config: 
     override-none: true 
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
feign:
  hystrix: 
   enabled: true


server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka1:2001/eureka
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

    
